### ISSUE TITLE
Some problems about README.md

### ISSUE THREAD

**Issue by sousoul** [ILLIXR/visual_postprocessing#1]
Hi, @Zee2  @mhuzai  thanks for your work!

But i meet some problems when I am trying to run the code, i follow README.md in **ILLIXR/vistual_postprocessing**, and successfully compiled the project with the included makefile. But i do not understand what you mean 

> Run with ./fbo and the desired background image

So i just type `./fbo` but i get the output `Usage: ./test1 [image]`, it seems that i don't use it correctly when i check the source code. So how can we correct this error?

I will appreciate it for your reply!

**Comment by mhuzai** [comment]
Hey, @sousoul, thank you for using ILLIXR!

The binary takes as input an image. We have provided two examples in the repo: landscape.png and museum.png So for instance, you would do `./fbo /path/to/landscape.png`

We have updated the documentation to reflect this. Let us know if you have any more questions.

**Comment by sousoul** [comment]
Thanks for your reply! @mhuzai 

When i add the path to landscape.png, i get the output like this 
```
X Error of failed request:  GLXBadFBConfig
  Major opcode of failed request:  146 (GLX)
  Minor opcode of failed request:  34 ()
  Serial number of failed request:  25
  Current serial number in output stream:  26
```
My opengl version is
```
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
OpenGL version string: 1.4 (2.1 Mesa 10.5.4)
```
and the GPU driver version is 440.36, and I am on I'm on Ubuntu 16.04.6 LTS. I am new to OpenGL and VR domain, maybe the error is cuased by the wrong version of OpenGL?

**Comment by mhuzai** [comment]
This was due to a bug in our image loader. We have pushed a fix. Please give it a shot and let us know!

**Comment by sousoul** [comment]
I type `./fbo ../src/museum.png`  again, the error remains 
```
X Error of failed request:  GLXBadFBConfig
  Major opcode of failed request:  146 (GLX)
  Minor opcode of failed request:  34 ()
  Serial number of failed request:  25
  Current serial number in output stream:  26
```

but when i typed `./test1 ../museum.png` , i got an image
![60db8c7aa02e958b982a4234d419144](https://user-images.githubusercontent.com/49592082/77714361-cb8e1f80-7013-11ea-809c-8e05a7e0b0e2.png)
and I also try the other two images, landscape.png and tundra.png, I got 

![image](https://user-images.githubusercontent.com/49592082/77714471-0e4ff780-7014-11ea-8b6e-0fce6e4adc03.png)
![image](https://user-images.githubusercontent.com/49592082/77714492-1c9e1380-7014-11ea-84ca-da4f9a3af1ef.png)

**Comment by Zee2** [comment]
Hi,

This looks to be because you're using some kind of X forwarding? GLX doesn't usually play nice with forwarding like that. Try running in a native Linux environment. Right now, ILLIXR only supports Linux.

- Finn

**Comment by sousoul** [comment]
Thanks for your reply！ @Zee2 
I will have a try on a native Linux environment!
